server:
  port: 4444


spring:
  application:
    name: CHAT-NOTIFICATION-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://aabhivishnu:fNWzcCov7zwfBcpK@cluster0.o3iw1py.mongodb.net/Event_Rabbiter_Chat_Service
eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/